# Generated by Django 4.2.15 on 2024-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='app_blog_co_created_15b33d_idx'),
        ),
    ]
